spring:
  datasource:
    url: jdbc:h2:file:.\src\main\resources\data\base;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
  servlet:
    context-path: